// This file is generated by typesafe-i18n (run i18n:extract or i18n:watch). Stub below for initial compile.
/* eslint-disable */
export type BaseTranslation = Record<string, unknown>;
export type BaseLocale = 'en';
export type Locales = 'en' | 'ru' | 'sk';
export type Translation = BaseTranslation;
export type Translations = BaseTranslation;
export type Formatters = Record<string, unknown>;
export type TranslationFunctions = Record<string, unknown>;
